// Code generated by MockGen. DO NOT EDIT.
// Source: endpoint.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/art-es/blog/internal/auth/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockuserRegisterCase is a mock of userRegisterCase interface.
type MockuserRegisterCase struct {
	ctrl     *gomock.Controller
	recorder *MockuserRegisterCaseMockRecorder
}

// MockuserRegisterCaseMockRecorder is the mock recorder for MockuserRegisterCase.
type MockuserRegisterCaseMockRecorder struct {
	mock *MockuserRegisterCase
}

// NewMockuserRegisterCase creates a new mock instance.
func NewMockuserRegisterCase(ctrl *gomock.Controller) *MockuserRegisterCase {
	mock := &MockuserRegisterCase{ctrl: ctrl}
	mock.recorder = &MockuserRegisterCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRegisterCase) EXPECT() *MockuserRegisterCaseMockRecorder {
	return m.recorder
}

// Use mocks base method.
func (m *MockuserRegisterCase) Use(ctx context.Context, in *dto.UserRegisterIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockuserRegisterCaseMockRecorder) Use(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockuserRegisterCase)(nil).Use), ctx, in)
}
