// Code generated by MockGen. DO NOT EDIT.
// Source: case_user_activate.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/art-es/blog/internal/auth/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockuserActivator is a mock of userActivator interface.
type MockuserActivator struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivatorMockRecorder
}

// MockuserActivatorMockRecorder is the mock recorder for MockuserActivator.
type MockuserActivatorMockRecorder struct {
	mock *MockuserActivator
}

// NewMockuserActivator creates a new mock instance.
func NewMockuserActivator(ctrl *gomock.Controller) *MockuserActivator {
	mock := &MockuserActivator{ctrl: ctrl}
	mock.recorder = &MockuserActivatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivator) EXPECT() *MockuserActivatorMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockuserActivator) Activate(ctx context.Context, activationCode string, tx domain.TxCommitter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, activationCode, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockuserActivatorMockRecorder) Activate(ctx, activationCode, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockuserActivator)(nil).Activate), ctx, activationCode, tx)
}
