// Code generated by MockGen. DO NOT EDIT.
// Source: endpoint.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/art-es/blog/internal/auth/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockuserAuthenticateCase is a mock of userAuthenticateCase interface.
type MockuserAuthenticateCase struct {
	ctrl     *gomock.Controller
	recorder *MockuserAuthenticateCaseMockRecorder
}

// MockuserAuthenticateCaseMockRecorder is the mock recorder for MockuserAuthenticateCase.
type MockuserAuthenticateCaseMockRecorder struct {
	mock *MockuserAuthenticateCase
}

// NewMockuserAuthenticateCase creates a new mock instance.
func NewMockuserAuthenticateCase(ctrl *gomock.Controller) *MockuserAuthenticateCase {
	mock := &MockuserAuthenticateCase{ctrl: ctrl}
	mock.recorder = &MockuserAuthenticateCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserAuthenticateCase) EXPECT() *MockuserAuthenticateCaseMockRecorder {
	return m.recorder
}

// Use mocks base method.
func (m *MockuserAuthenticateCase) Use(ctx context.Context, in *dto.UserAuthenticateIn) (*dto.UserAuthenticateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", ctx, in)
	ret0, _ := ret[0].(*dto.UserAuthenticateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Use indicates an expected call of Use.
func (mr *MockuserAuthenticateCaseMockRecorder) Use(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockuserAuthenticateCase)(nil).Use), ctx, in)
}
